### ISSUE TITLE
超时提示优化

### ISSUE THREAD

**Issue by jeho0815** [huaweicloud/huaweicloud-sdk-java-obs#1]
发生超时之后，没有任何地址和具体的超时时间信息
```
[ERROR][ vert.x-eventloop-thread-7][2019-03-06 11:16:03.544] c.c.h.s.CommonDispatcher[44] - handle POST /rest/guidemgr/v1/manage/article/upload/picture fail
com.obs.services.exception.ObsException: Error message:Request error. OBS servcie Error Message.
	at com.obs.services.internal.utils.ServiceUtils.changeFromServiceException(ServiceUtils.java:731)
	at com.obs.services.ObsClient.doActionWithResult(ObsClient.java:2484)
	at com.obs.services.ObsClient.initiateMultipartUpload(ObsClient.java:2147)
	at com.obs.services.internal.ResumableClient.prepare(ResumableClient.java:338)
	at com.obs.services.internal.ResumableClient.uploadFileCheckPoint(ResumableClient.java:129)
	at com.obs.services.internal.ResumableClient.uploadFileResume(ResumableClient.java:69)
	at com.obs.services.ObsClient.uploadFile(ObsClient.java:1632)
	at cse.guide.manager.service.impl.GuideServiceImpl.uploadPicture(GuideServiceImpl.java:413)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at com.obs.services.internal.RestStorageService.performRequest(RestStorageService.java:420)
	at com.obs.services.internal.RestStorageService.performRequestWithoutSignature(RestStorageService.java:382)
	at com.obs.services.internal.RestStorageService.performRestForApiVersion(RestStorageService.java:760)
	at com.obs.services.internal.ObsService.getAuthTypeNegotiationResponseImpl(ObsService.java:2853)
	at com.obs.services.internal.ObsService.parseAuthTypeInResponse(ObsService.java:2837)
	at com.obs.services.internal.ObsService.getApiVersion(ObsService.java:2824)
	at com.obs.services.ObsClient.access$8000(ObsClient.java:150)
	at com.obs.services.ObsClient$ActionCallbackWithResult.authTypeNegotiate(ObsClient.java:2456)
	at com.obs.services.ObsClient.doActionWithResult(ObsClient.java:2470)
	... 13 common frames omitted
```

**Comment by x00403408** [comment]
非问题，异常是底层库抛出
