### ISSUE TITLE
ObsClient.createBucket error:Error message:Request Error.OBS servcie Error Message. -- ResponseCode: 400, ResponseStatus: Bad Reques

### ISSUE THREAD

**Issue by sitJac** [huaweicloud/huaweicloud-sdk-java-obs#101]
```
Exception in thread "main" com.obs.services.exception.ObsException: Error message:Request Error.OBS servcie Error Message. -- ResponseCode: 400, ResponseStatus: Bad Request, XML Error Message: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><Error><Code>IllegalLocationConstraintException</Code><Message>The  location constraint is incompatible for the region specific endpoint this request was sent to.</Message><RequestId>000001827CD64B3B92CC6E46800BEC44</RequestId><HostId>AEF4iILd0Us0T1AlvVBRvrRYYdMpxQihA9vB6SgGOxQNnCfbrJcI+sS6kSothQK5</HostId></Error>
	at com.obs.services.internal.utils.ServiceUtils.changeFromServiceException(ServiceUtils.java:753)
	at com.obs.services.ObsClient.doActionWithResult(ObsClient.java:2702)
	at com.obs.services.ObsClient.createBucket(ObsClient.java:535)
	at com.obs.services.ObsClient.createBucket(ObsClient.java:526)
	at com.obs.services.ObsClient.createBucket(ObsClient.java:502)
	at com.ldq.hotch.api.obs.main(obs.java:16)
```

**Comment by daotianxiyang** [comment]
最后怎么解决的？

**Comment by 1010663814** [comment]
华为的东西就是BUG多，我也遇到这BUG了。
