### ISSUE TITLE
上传20次有一次失败,NullPointerException

### ISSUE THREAD

**Issue by AIMWLI** [huaweicloud/huaweicloud-sdk-java-obs#107]
java.lang.NullPointerException

 	at com.obs.services.internal.RestStorageService.getIHeaders(RestStorageService.java:1051)

 	at com.obs.services.internal.RestStorageService.getRestHeaderPrefix(RestStorageService.java:730)

 	at com.obs.services.internal.RestStorageService.handleThrowable(RestStorageService.java:208)

 	at com.obs.services.internal.RestStorageService.performRequest(RestStorageService.java:407)

 	at com.obs.services.internal.RestStorageService.performRequest(RestStorageService.java:388)

 	at com.obs.services.internal.service.ObsObjectBaseService.putObjectImpl(ObsObjectBaseService.java:106)

 	at com.obs.services.AbstractObjectClient.access$800(AbstractObjectClient.java:53)

 	at com.obs.services.AbstractObjectClient$5.action(AbstractObjectClient.java:284)

 	at com.obs.services.AbstractObjectClient$5.action(AbstractObjectClient.java:278)

 	at com.obs.services.AbstractClient.doActionWithResult(AbstractClient.java:392)

 	at com.obs.services.AbstractObjectClient.putObject(AbstractObjectClient.java:277)

**Comment by zzq996** [comment]
试下用单例的client呢

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

⏰ 已 1014 天无活动，标记为过期。如有更新将自动取消。30 天后无活动将自动关闭。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

🔒 因 35 天无活动自动关闭。如需重新打开请评论。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>
