### ISSUE TITLE
com.obs.services.internal.utils.ServiceUtils.changeFromServiceException

### ISSUE THREAD

**Issue by alex-github168** [huaweicloud/huaweicloud-sdk-java-obs#125]
com.obs.services.exception.ObsException: Error message:Request Error.OBS servcie Error Message.
        at com.obs.services.internal.utils.ServiceUtils.changeFromServiceException(ServiceUtils.java:533)
        at com.obs.services.AbstractClient.doActionWithResult(AbstractClient.java:402)
        at com.obs.services.AbstractObjectClient.putObject(AbstractObjectClient.java:279)
        at com.obs.services.AbstractObjectClient.putObject(AbstractObjectClient.java:253)

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

⏰ 已 1201 天无活动，标记为过期。如有更新将自动取消。30 天后无活动将自动关闭。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

🔒 因 35 天无活动自动关闭。如需重新打开请评论。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>
