### ISSUE TITLE
调用失败ResponseCode: 404

### ISSUE THREAD

**Issue by awei12121** [huaweicloud/huaweicloud-sdk-java-obs#137]
代码：
        ObsClient obsClient = new ObsClient(ak, sk,endPoint);
        String bucketname = "gadad";
        String objectkey = "4.png";
        PutObjectResult res = obsClient.putObject(bucketname, objectkey, new File("F:/bug/4.png"));
        String objectUrl = res.getObjectUrl();
        System.out.println("url:"+objectUrl);
报错：
Exception in thread "main" com.obs.services.exception.ObsException: Error message:Request Error.OBS service Error Message. -- ResponseCode: 404, ResponseStatus: Not Found, RequestId: 0000018B37BA186B47CE0A3CC6268D32, HostId: 32AAAQAAEAABAAAQAAEAABAAAQAAEAABCSBprWHCBsvTUqaWM2xubIYCYVkWSgAz
	at com.obs.services.internal.utils.ServiceUtils.changeFromServiceException(ServiceUtils.java:544)
	at com.obs.services.AbstractClient.doActionWithResult(AbstractClient.java:403)
	at com.obs.services.AbstractObjectClient.putObject(AbstractObjectClient.java:284)
	at com.obs.services.AbstractObjectClient.putObject(AbstractObjectClient.java:321)
	at com.obs.services.AbstractObjectClient.putObject(AbstractObjectClient.java:304)
	at com.tpri.ne.sync.controller.TestObs.main(TestObs.java:29)

**Comment by NoAccident** [comment]
404文件找不到；F:\\bug\\4.png 或者再看下路径是否正确

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

⏰ 已 1017 天无活动，标记为过期。如有更新将自动取消。30 天后无活动将自动关闭。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

🔒 因 35 天无活动自动关闭。如需重新打开请评论。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>
