### ISSUE TITLE
OBS service Error Message. Failed to build XML document

### ISSUE THREAD

**Issue by lifw555** [huaweicloud/huaweicloud-sdk-java-obs#154]
编译jdk版本：jdk8
运行jdk版本：jdk21
obs版本：esdk-obs-java-bundle 3.23.9.1

查了资料，可能是和xalan冲突。

```
2024-05-20 01:00:18.576 ERROR --- [ScheduledTask-9] com.abc.file.hwobs.abc [441] : 删除失败：abc/abc/def/

com.obs.services.exception.ObsException: OBS service Error Message. Failed to build XML document
        at com.obs.services.internal.utils.ServiceUtils.changeFromServiceException(ServiceUtils.java:540) ~[esdk-obs-java-bundle-3.23.9.1.jar:?]
        at com.obs.services.AbstractClient.doActionWithResult(AbstractClient.java:398) ~[esdk-obs-java-bundle-3.23.9.1.jar:?]
        at com.obs.services.AbstractObjectClient.deleteObjects(AbstractObjectClient.java:489) ~[esdk-obs-java-bundle-3.23.9.1.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.33.jar:5.3.33]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.33.jar:5.3.33]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) ~[spring-context-5.3.33.jar:5.3.33]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD
        at org.docx4j.org.apache.xalan.processor.TransformerFactoryImpl.setAttribute(TransformerFactoryImpl.java:571) ~[xalan-interpretive-8.0.0.jar:?]
        at com.obs.services.internal.xml.OBSXMLBuilder.asString(OBSXMLBuilder.java:306) ~[esdk-obs-java-bundle-3.23.9.1.jar:?]
        at com.obs.services.internal.V2Convertor.transKeyAndVersion(V2Convertor.java:412) ~[esdk-obs-java-bundle-3.23.9.1.jar:?]
        at com.obs.services.internal.service.ObsObjectBaseService.deleteObjectsImpl(ObsObjectBaseService.java:314) ~[esdk-obs-java-bundle-3.23.9.1.jar:?]
        at com.obs.services.AbstractObjectClient.access$1600(AbstractObjectClient.java:60) ~[esdk-obs-java-bundle-3.23.9.1.jar:?]
        at com.obs.services.AbstractObjectClient$10.action(AbstractObjectClient.java:494) ~[esdk-obs-java-bundle-3.23.9.1.jar:?]
        at com.obs.services.AbstractObjectClient$10.action(AbstractObjectClient.java:490) ~[esdk-obs-java-bundle-3.23.9.1.jar:?]
        at com.obs.services.AbstractClient.doActionWithResult(AbstractClient.java:388) ~[esdk-obs-java-bundle-3.23.9.1.jar:?]
```

**Comment by zzq996** [comment]
改用其他版本试下

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

⏰ 已 803 天无活动，标记为过期。如有更新将自动取消。30 天后无活动将自动关闭。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

🔒 因 35 天无活动自动关闭。如需重新打开请评论。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>
