### ISSUE TITLE
getObjectTagging报错NoSuchTagSet

### ISSUE THREAD

**Issue by li-yuyu** [huaweicloud/huaweicloud-sdk-java-obs#162]
查询对象标签在无标签的情况下会报错，查不到应该返回空不是报错吧
com.obs.services.exception.ObsException: Error message:Request Error.OBS service Error Message. -- ResponseCode: 404, ResponseStatus: Not Found, XML Error Message: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><Error><Code>NoSuchTagSet</Code><Message>The TagSet does not exist</Message><RequestId>00000191DF13A30DCA062BA4ED5AB77A</RequestId><HostId>qzBE1rYIduYFO07VFlYdfwDAP18DlQ/7ZOXaLQwvseQqw6IMAUcVgRg8cW4YGOgx</HostId></Error>
	at com.obs.services.internal.utils.ServiceUtils.changeFromServiceException(ServiceUtils.java:544)
	at com.obs.services.AbstractClient.doActionWithResult(AbstractClient.java:403)
	at com.obs.services.AbstractObjectClient.getObjectTagging(AbstractObjectClient.java:769)
	at com.noahwm.noahwm_fs.manager.ObsManager.addTag(ObsManager.java:588)
	... 32 more

**Comment by liqiuqiu111** [comment]
esdk的处理逻辑如此，服务端返回404，not found ,esdk不会再进行处理。

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

⏰ 已 683 天无活动，标记为过期。如有更新将自动取消。30 天后无活动将自动关闭。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

🔒 因 35 天无活动自动关闭。如需重新打开请评论。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>
