### ISSUE TITLE
建议更换掉 com.obs.services.internal.utils.ReflectUtils 里的 sun.misc.BASE64Encoder 、BASE64Decoder

### ISSUE THREAD

**Issue by JohnVX** [huaweicloud/huaweicloud-sdk-java-obs#39]
sun.misc 不是 java 标准公开的 API ，在一些环境下会加载不到这些类。有 apache commons 或者 spring 的 BASE64 工具可供替换。

java.lang.ClassNotFoundException: sun.misc.BASE64Encoder
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[microservice-1.0.0.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Unknown Source) ~[?:?]
        at com.obs.services.internal.utils.ReflectUtils.<clinit>(ReflectUtils.java:73) [esdk-obs-java-3.20.6.jar!/:?]
        at com.obs.services.internal.utils.ServiceUtils.toBase64(ServiceUtils.java:407) [esdk-obs-java-3.20.6.jar!/:?]
        at com.obs.services.internal.utils.ServiceUtils.signWithHmacSha1(ServiceUtils.java:184) [esdk-obs-java-3.20.6.jar!/:?]
        at com.obs.services.internal.utils.AbstractAuthentication.caculateSignature(AbstractAuthentication.java:38) [esdk-obs-java-3.20.6.jar!/:?]
        at com.obs.services.internal.utils.AbstractAuthentication.makeAuthorizationString(AbstractAuthentication.java:53) [esdk-obs-java-3.20.6.jar!/:?]
        at com.obs.services.internal.RestStorageService.authorizeHttpRequest(RestStorageService.java:934) [esdk-obs-java-3.20.6.jar!/:?]
        at com.obs.services.internal.RestStorageService.performRequest(RestStorageService.java:618) [esdk-obs-java-3.20.6.jar!/:?]
        at com.obs.services.internal.RestStorageService.performRestGet(RestStorageService.java:982) [esdk-obs-java-3.20.6.jar!/:?]
        at com.obs.services.internal.RestStorageService.performRestGet(RestStorageService.java:961) [esdk-obs-java-3.20.6.jar!/:?]
        at com.obs.services.internal.ObsService.listObjectsImpl(ObsService.java:2124) [esdk-obs-java-3.20.6.jar!/:?]
        at com.obs.services.ObsClient.access$1500(ObsClient.java:211) [esdk-obs-java-3.20.6.jar!/:?]
        at com.obs.services.ObsClient$4.action(ObsClient.java:881) [esdk-obs-java-3.20.6.jar!/:?]
        at com.obs.services.ObsClient$4.action(ObsClient.java:878) [esdk-obs-java-3.20.6.jar!/:?]
        at com.obs.services.ObsClient.doActionWithResult(ObsClient.java:3929) [esdk-obs-java-3.20.6.jar!/:?]
        at com.obs.services.ObsClient.listObjects(ObsClient.java:877) [esdk-obs-java-3.20.6.jar!/:?]

**Comment by JohnVX** [comment]
建议在 ReflectUtils  类初始化的时候总体判断下，有可以用的 encoder decoder 就不用把异常调用栈打印出来了

**Comment by mpb159753** [comment]
新版本已经加了捕获
