### ISSUE TITLE
JDK11下sun.misc.BASE64Decoder class not found问题

### ISSUE THREAD

**Issue by haimingwey** [huaweicloud/huaweicloud-sdk-java-obs#43]
JDK11下sun.misc.BASE64Decoder class not found问题
obs sdk版本：com.huaweicloud:esdk-obs-java:3.20.6.1

java.lang.ClassNotFoundException: sun.misc.BASE64Decoder 
        at java.base/java.lang.Class.forNameImpl(Native Method) 
        at java.base/java.lang.Class.forName(Class.java:343) 
        at com.obs.services.internal.utils.ReflectUtils.<clinit>(ReflectUtils.java:79) 
        at com.obs.services.internal.utils.ServiceUtils.toBase64(ServiceUtils.java:407) 
        at com.obs.services.internal.utils.ServiceUtils.signWithHmacSha1(ServiceUtils.java:184) 
        at com.obs.services.internal.utils.AbstractAuthentication.caculateSignature(AbstractAuthentication.java:38) 
        at com.obs.services.internal.utils.AbstractAuthentication.makeAuthorizationString(AbstractAuthentication.java:53) 
        at com.obs.services.internal.RestStorageService.authorizeHttpRequest(RestStorageService.java:934) 
        at com.obs.services.internal.RestStorageService.performRequest(RestStorageService.java:618) 
        at com.obs.services.internal.RestStorageService.performRestGet(RestStorageService.java:982) 
        at com.obs.services.internal.RestStorageService.performRestGet(RestStorageService.java:961) 
        at com.obs.services.internal.ObsService.listObjectsImpl(ObsService.java:2124)

**Comment by wushugenzz** [comment]
一样的问题

**Comment by mpb159753** [comment]
3.21.4 可以不？ @wushugenzz @haimingwey

**Comment by wushugenzz** [comment]
可以了，之前是自己的原因。
感谢你得回复



在 2021-06-07 10:50:37，"mpb159753" ***@***.***> 写道：

3.21.4 可以不？ @***@***.***

**Comment by haimingwey** [comment]
3.21.4

> 3.21.4 可以不？ @wushugenzz @haimingwey

3.21.4可以，谢谢。
