### ISSUE TITLE
NoSuchMethodError: okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody

### ISSUE THREAD

**Issue by HardCore20** [huaweicloud/huaweicloud-sdk-java-obs#54]
按照官网案例编码,结果报错🤣🤣

try(ObsClient obsClient = new ObsClient(accessKey, securityKey, obsUrl)){
            obsClient.deleteObject(bucketName, "foo.mp4");
        }catch (Exception e){
            logger.error(e.getMessage());
        }
}

java.lang.NoSuchMethodError: okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;

	at com.obs.services.internal.RestConnectionService.createRequestBuilder(RestConnectionService.java:171)
	at com.obs.services.internal.RestConnectionService.setupConnection(RestConnectionService.java:162)
	at com.obs.services.internal.RestStorageService.performRestForApiVersion(RestStorageService.java:1000)
	at com.obs.services.internal.service.AbstractRequestConvertor.getAuthTypeNegotiationResponseImpl(AbstractRequestConvertor.java:355)
	at com.obs.services.internal.service.AbstractRequestConvertor.parseAuthTypeInResponse(AbstractRequestConvertor.java:338)
	at com.obs.services.internal.service.AbstractRequestConvertor.getApiVersion(AbstractRequestConvertor.java:302)
	at com.obs.services.AbstractClient.access$000(AbstractClient.java:56)
	at com.obs.services.AbstractClient$ActionCallbackWithResult.authTypeNegotiate(AbstractClient.java:370)
	at com.obs.services.AbstractClient.doActionWithResult(AbstractClient.java:384)
	at com.obs.services.AbstractObjectClient.deleteObject(AbstractObjectClient.java:392)
	at com.obs.services.AbstractObjectClient.deleteObject(AbstractObjectClient.java:380)

依赖版本

        <dependency>
            <groupId>com.huawei.apigateway</groupId>
            <artifactId>java-sdk-core</artifactId>
            <version>3.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.huaweicloud</groupId>
            <artifactId>esdk-obs-java</artifactId>
            <version>3.21.8</version>
        </dependency>

**Comment by HardCore20** [comment]
好家伙,降版本就解决了.


        <dependency>
            <groupId>com.huaweicloud</groupId>
            <artifactId>esdk-obs-java</artifactId>
            <version>3.20.6.1</version>
        </dependency>

**Comment by mpb159753** [comment]
你是不是也用了 spring-boot？spring boot 指定了三方依赖版本，导致 sdk 引入的 okhttp 版本不正确，可以显式的引入 okhttp 4.8.0 版本解决。
另外不要用 3.20.6.1，这个版本依赖的 okhttp 存在问题，准确的说，所有 okhttp 3.X 版本都有问题，可能会多线程时串流，已经反馈给官方，官方表示 okhttp 4.x 版本里修复，不再管 3.x 了
