### ISSUE TITLE
分段上传最后合并出错 obsClient.completeMultipartUpload

### ISSUE THREAD

**Issue by gangganghao1016** [huaweicloud/huaweicloud-sdk-java-obs#62]
引入方式 implementation 'com.huaweicloud:esdk-obs-android:3.21.8'
版本 3.21.8
2021-11-26 14:13:11.900 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err: ERROR StatusLogger Could not reconfigure JMX
2021-11-26 14:13:11.900 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:  java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory;
2021-11-26 14:13:11.900 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
2021-11-26 14:13:11.900 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:629)
2021-11-26 14:13:11.900 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:691)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:243)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:669)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at com.obs.log.LoggerBuilder.getLogger(LoggerBuilder.java:53)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at com.obs.log.LoggerBuilder.getLogger(LoggerBuilder.java:62)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at com.obs.services.internal.RestConnectionService.<clinit>(RestConnectionService.java:42)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at com.maezia.ezia.composer.phoneapp.uploader.UploaderManager$UploadToObsTask.uploadInitiateMultipart(UploaderManager.java:379)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at com.maezia.ezia.composer.phoneapp.uploader.UploaderManager$UploadToObsTask.doInBackground(UploaderManager.java:274)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at com.maezia.ezia.composer.phoneapp.uploader.UploaderManager$UploadToObsTask.doInBackground(UploaderManager.java:209)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2021-11-26 14:13:11.901 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at java.lang.Thread.run(Thread.java:764)
2021-11-26 14:13:11.902 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.management.ManagementFactory" on path: DexPathList[[zip file "/data/app/com.maezia.ezia.composer.phoneapp-x45qbK9IiA0pRNPJmRi-ug==/base.apk"],nativeLibraryDirectories=[/data/app/com.maezia.ezia.composer.phoneapp-x45qbK9IiA0pRNPJmRi-ug==/lib/arm64, /system/lib64, /system/vendor/lib64]]
2021-11-26 14:13:11.902 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
2021-11-26 14:13:11.902 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2021-11-26 14:13:11.902 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2021-11-26 14:13:11.902 10715-11891/com.maezia.ezia.composer.phoneapp W/System.err: 	... 22 more
2021-11-26 14:13:12.765 10715-11891/com.maezia.ezia.composer.phoneapp I/UploadPart: 	0000017D5AE05619804FD51858E1A3F4
2021-11-26 14:13:12.801 10715-10738/com.maezia.ezia.composer.phoneapp I/zygote64: Do full code cache collection, code=1006KB, data=643KB
2021-11-26 14:13:12.804 10715-10738/com.maezia.ezia.composer.phoneapp I/zygote64: After code cache collection, code=945KB, data=539KB
2021-11-26 14:13:28.296 10715-11897/com.maezia.ezia.composer.phoneapp I/UploadPart: Part#4 done
2021-11-26 14:13:41.383 10715-11894/com.maezia.ezia.composer.phoneapp I/UploadPart: Part#1 done
2021-11-26 14:13:48.841 10715-11896/com.maezia.ezia.composer.phoneapp I/UploadPart: Part#3 done
2021-11-26 14:13:53.241 10715-11895/com.maezia.ezia.composer.phoneapp I/UploadPart: Part#2 done
    
    
    --------- beginning of crash
2021-11-26 14:13:53.259 10715-11891/com.maezia.ezia.composer.phoneapp E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
    Process: com.maezia.ezia.composer.phoneapp, PID: 10715
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: javax.xml.parsers.FactoryConfigurationError: Provider com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl not found
        at com.obs.services.internal.xml.OBSXMLBuilder.newInstance(OBSXMLBuilder.java:146)
        at com.obs.services.internal.xml.OBSXMLBuilder.findDocumentBuilderFactory(OBSXMLBuilder.java:59)
        at com.obs.services.internal.xml.OBSXMLBuilder.createDocumentImpl(OBSXMLBuilder.java:66)
        at com.obs.services.internal.xml.OBSXMLBuilder.create(OBSXMLBuilder.java:153)
        at com.obs.services.internal.V2Convertor.transCompleteMultipartUpload(V2Convertor.java:78)
        at com.obs.services.internal.service.ObsMultipartObjectService.completeMultipartUploadImpl(ObsMultipartObjectService.java:93)
        at com.obs.services.AbstractMultipartObjectClient.access$400(AbstractMultipartObjectClient.java:39)
        at com.obs.services.AbstractMultipartObjectClient$5.action(AbstractMultipartObjectClient.java:185)
        at com.obs.services.AbstractMultipartObjectClient$5.action(AbstractMultipartObjectClient.java:182)
        at com.obs.services.AbstractClient.doActionWithResult(AbstractClient.java:388)
        at com.obs.services.AbstractMultipartObjectClient.completeMultipartUpload(AbstractMultipartObjectClient.java:181)
        at com.maezia.ezia.composer.phoneapp.uploader.UploaderManager$UploadToObsTask.uploadInitiateMultipart(UploaderManager.java:451)
        at com.maezia.ezia.composer.phoneapp.uploader.UploaderManager$UploadToObsTask.doInBackground(UploaderManager.java:274)
        at com.maezia.ezia.composer.phoneapp.uploader.UploaderManager$UploadToObsTask.doInBackground(UploaderManager.java:209)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
    
    
    --------- beginning of system

**Comment by liaofuda** [comment]
您好，请问下只有调用合并段接口的时候，会报这个错么？报错是否是必现的呢？

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

⏰ 已 1013 天无活动，标记为过期。如有更新将自动取消。30 天后无活动将自动关闭。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

🔒 因 35 天无活动自动关闭。如需重新打开请评论。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>
