### ISSUE TITLE
上传文件错误java.lang.NoClassDefFoundError: com.obs.services.internal.RestStorageService$$ExternalSyntheticLambda0

### ISSUE THREAD

**Issue by zhoumiao123** [huaweicloud/huaweicloud-sdk-java-obs#91]
java.lang.NoClassDefFoundError: com.obs.services.internal.RestStorageService$$ExternalSyntheticLambda0
        at com.obs.services.internal.RestStorageService.performRequest(RestStorageService.java:399)
        at com.obs.services.internal.RestStorageService.performRequest(RestStorageService.java:388)
        at com.obs.services.internal.service.ObsObjectBaseService.putObjectImpl(ObsObjectBaseService.java:106)
        at com.obs.services.AbstractObjectClient.access$800(AbstractObjectClient.java:53)
        at com.obs.services.AbstractObjectClient$5.action(AbstractObjectClient.java:284)
        at com.obs.services.AbstractObjectClient$5.action(AbstractObjectClient.java:278)
        at com.obs.services.AbstractClient.doActionWithResult(AbstractClient.java:392)
        at com.obs.services.AbstractObjectClient.putObject(AbstractObjectClient.java:277)

**Comment by whyrookie** [comment]
遇到一样的问题，Android版本5.0

**Comment by zhoumiao123** [comment]
> 遇到一样的问题，Android版本5.0

跟客服沟通了，他们只支持7.0及以上。

**Comment by whyrookie** [comment]
> > 遇到一样的问题，Android版本5.0
> 
> 跟客服沟通了，他们只支持7.0及以上。

多谢解答

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

⏰ 已 1473 天无活动，标记为过期。如有更新将自动取消。30 天后无活动将自动关闭。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

🔒 因 35 天无活动自动关闭。如需重新打开请评论。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>
